#!/bin/bash
# Pre-tool-use hook: block edits to auto-generated / gitignored directories
set -e
INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.toolName')

# Only check file-modifying tools
if [ "$TOOL_NAME" != "edit" ] && [ "$TOOL_NAME" != "create" ]; then
  exit 0
fi

FILE_PATH=$(echo "$INPUT" | jq -r '.toolArgs' | jq -r '.path // empty')
if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Block edits to manifests/ (auto-generated deployment artifacts)
if echo "$FILE_PATH" | grep -qE '(^|/)manifests/'; then
  jq -nc '{permissionDecision: "deny", permissionDecisionReason: "manifests/ is auto-generated by Deploy-Lab.ps1 — do not edit manually"}'
  exit 0
fi

# Block edits to logs/ (auto-generated transcripts)
if echo "$FILE_PATH" | grep -qE '(^|/)logs/'; then
  jq -nc '{permissionDecision: "deny", permissionDecisionReason: "logs/ contains auto-generated transcripts — do not edit manually"}'
  exit 0
fi
